-- DDL generated by Postico 1.5.12
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE users (
    id SERIAL PRIMARY KEY,
    handle text UNIQUE,
    email text UNIQUE,
    public_id text NOT NULL UNIQUE,
    password text,
    props jsonb DEFAULT '{}'::jsonb,
    deleted boolean DEFAULT false
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX users_pkey ON users(id int4_ops);
CREATE UNIQUE INDEX users_handle_key ON users(handle text_ops);
CREATE UNIQUE INDEX users_email_key ON users(email text_ops);
CREATE UNIQUE INDEX users_public_id_key ON users(public_id text_ops);
CREATE UNIQUE INDEX cusers_pkey ON users(id int4_ops);
CREATE UNIQUE INDEX cusers_handle_key ON users(handle text_ops);
CREATE UNIQUE INDEX cusers_email_key ON users(email text_ops);
CREATE UNIQUE INDEX cusers_public_id_key ON users(public_id text_ops);
CREATE UNIQUE INDEX cspiel_users_pkey ON users(id int4_ops);
CREATE UNIQUE INDEX cspiel_users_handle_key ON users(handle text_ops);
CREATE UNIQUE INDEX cspiel_users_email_key ON users(email text_ops);
CREATE UNIQUE INDEX cspiel_users_public_id_key ON users(public_id text_ops);



-- DDL generated by Postico 1.5.12
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE channels (
    id SERIAL PRIMARY KEY,
    title text,
    slug text,
    timestamp bigint,
    last_played bigint,
    settings jsonb
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX channels_pkey ON channels(id int4_ops);
CREATE INDEX channels_slug_idx ON channels(slug text_ops);




-- DDL generated by Postico 1.5.12
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE rounds (
    id SERIAL PRIMARY KEY,
    user_id integer REFERENCES users(id) ON DELETE CASCADE,
    timestamp bigint,
    channel_id integer REFERENCES channels(id) ON DELETE SET NULL,
    status text
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX rounds_pkey ON rounds(id int4_ops);
CREATE INDEX rounds_channel_id_idx ON rounds(channel_id int4_ops);
