-- DDL generated by Postico 1.5.12
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE users (
    id SERIAL PRIMARY KEY,
    handle text UNIQUE,
    email text UNIQUE,
    public_id text NOT NULL UNIQUE,
    password text,
    props jsonb DEFAULT '{}'::jsonb,
    deleted boolean DEFAULT false
);
-- DDL generated by Postico 1.5.12
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE channels (
    id SERIAL PRIMARY KEY,
    title text,
    slug text,
    timestamp bigint,
    last_played bigint,
    settings jsonb
);
-- DDL generated by Postico 1.5.12
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE channel_users (
    id SERIAL PRIMARY KEY,
    user_id integer REFERENCES users(id),
    channel_id integer REFERENCES channels(id),
    timestamp bigint
);

-- Indices -------------------------------------------------------

CREATE INDEX channel_users_channel_id_idx ON channel_users(channel_id int4_ops);
CREATE UNIQUE INDEX channel_users_channel_id_user_id_idx ON channel_users(channel_id int4_ops,user_id int4_ops);


-- Indices -------------------------------------------------------

CREATE INDEX channels_slug_idx ON channels(slug text_ops);


-- DDL generated by Postico 1.5.12
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE rounds (
    id SERIAL PRIMARY KEY,
    user_id integer REFERENCES users(id) ON DELETE CASCADE,
    timestamp bigint,
    channel_id integer REFERENCES channels(id) ON DELETE SET NULL,
    status text DEFAULT 'open'::text,
    settings jsonb
);

-- Indices -------------------------------------------------------

CREATE INDEX rounds_channel_id_idx ON rounds(channel_id int4_ops);
CREATE INDEX rounds_user_id_idx ON rounds(user_id int4_ops);

-- DDL generated by Postico 1.5.12
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE turns (
    id SERIAL PRIMARY KEY,
    round_id integer REFERENCES rounds(id) ON DELETE CASCADE,
    user_id integer REFERENCES users(id),
    previous_turn_id integer,
    timestamp bigint,
    type text,
    contents text
);

-- Indices -------------------------------------------------------

CREATE INDEX turns_round_id_idx ON turns(round_id int4_ops);
CREATE INDEX turns_user_id_idx ON turns(user_id int4_ops);
CREATE INDEX turns_previous_turn_id_idx ON turns(previous_turn_id int4_ops);
